-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 23:09:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema friendlyplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friendlyplace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friendlyplace` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `friendlyplace` ;

-- -----------------------------------------------------
-- Table `friendlyplace`.`geographies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`geographies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'InnoDB free: 8192 kB';


-- -----------------------------------------------------
-- Table `friendlyplace`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`provinces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(2) CHARACTER SET 'utf8mb3' NOT NULL,
  `name_th` VARCHAR(150) CHARACTER SET 'utf8mb3' NOT NULL,
  `name_en` VARCHAR(150) CHARACTER SET 'utf8mb3' NOT NULL,
  `geography_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `pro_fk_geo` (`geography_id` ASC) VISIBLE,
  CONSTRAINT `pro_fk_geo`
    FOREIGN KEY (`geography_id`)
    REFERENCES `friendlyplace`.`geographies` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 78;


-- -----------------------------------------------------
-- Table `friendlyplace`.`amphures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`amphures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `name_th` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `name_en` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `province_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `amp_fk_pro` (`province_id` ASC) VISIBLE,
  CONSTRAINT `amp_fk_pro`
    FOREIGN KEY (`province_id`)
    REFERENCES `friendlyplace`.`provinces` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 1007
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `friendlyplace`.`districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`districts` (
  `id` VARCHAR(6) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `zip_code` INT NOT NULL,
  `name_th` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `name_en` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `amphure_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `dis_fk_amp` (`amphure_id` ASC) VISIBLE,
  CONSTRAINT `dis_fk_amp`
    FOREIGN KEY (`amphure_id`)
    REFERENCES `friendlyplace`.`amphures` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'InnoDB free: 8192 kB';


-- -----------------------------------------------------
-- Table `friendlyplace`.`resident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`resident` (
  `id_card` CHAR(13) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `districts_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_card`),
  INDEX `res_fk_dis` (`districts_id` ASC) VISIBLE,
  CONSTRAINT `res_fk_dis`
    FOREIGN KEY (`districts_id`)
    REFERENCES `friendlyplace`.`districts` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `friendlyplace`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`type` (
  `type_id` CHAR(2) NOT NULL,
  `price` INT NOT NULL,
  `type_desc` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `friendlyplace`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`room` (
  `room_id` CHAR(3) NOT NULL,
  `type_id` CHAR(2) NOT NULL,
  `room_status` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT 'out',
  `room_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `type_fk_room` (`type_id` ASC) VISIBLE,
  CONSTRAINT `type_fk_room`
    FOREIGN KEY (`type_id`)
    REFERENCES `friendlyplace`.`type` (`type_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `friendlyplace`.`lease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`lease` (
  `lease_id` INT NOT NULL AUTO_INCREMENT,
  `room_id` CHAR(3) NOT NULL,
  `id_card` CHAR(13) NOT NULL,
  `start_date_lease` DATE NOT NULL,
  `end_date_lease` DATE NULL DEFAULT NULL,
  `deposit` INT NOT NULL DEFAULT '5000',
  `discount` INT NOT NULL,
  `pet` CHAR(1) NOT NULL,
  `lease_status` VARCHAR(3) NOT NULL DEFAULT 'on',
  `member` INT NOT NULL,
  PRIMARY KEY (`lease_id`, `room_id`, `id_card`),
  INDEX `room_fk_makeL` (`room_id` ASC) VISIBLE,
  INDEX `res_fk_makeL` (`id_card` ASC) VISIBLE,
  CONSTRAINT `res_fk_makeL`
    FOREIGN KEY (`id_card`)
    REFERENCES `friendlyplace`.`resident` (`id_card`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `room_fk_makeL`
    FOREIGN KEY (`room_id`)
    REFERENCES `friendlyplace`.`room` (`room_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `friendlyplace`.`month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`month` (
  `pay_date` DATE NOT NULL,
  `last_pay_date` DATE NOT NULL,
  PRIMARY KEY (`pay_date`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `friendlyplace`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`unit` (
  `unit_id` INT NOT NULL,
  `unit_price` INT NOT NULL,
  `unit_desc` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`unit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `friendlyplace`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendlyplace`.`bill` (
  `bill_id` INT NOT NULL AUTO_INCREMENT,
  `pay_date` DATE NOT NULL,
  `lease_id` INT NOT NULL,
  `start_unit` INT NOT NULL,
  `end_unit` INT NOT NULL,
  `unit_id` INT NOT NULL,
  `water` INT NOT NULL DEFAULT '150',
  `electric` INT NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `pay_status` DATE NOT NULL,
  `charge` INT NOT NULL DEFAULT '0',
  `fridge_rent` INT NULL DEFAULT '0',
  `tv_rent` INT NULL DEFAULT '0',
  `laundry` INT NULL DEFAULT '0',
  PRIMARY KEY (`bill_id`, `pay_date`, `unit_id`, `lease_id`),
  INDEX `month_fk_payOn` (`pay_date` ASC) VISIBLE,
  INDEX `lease_fk_payOn` (`lease_id` ASC) VISIBLE,
  INDEX `unit_fk_payOn` (`unit_id` ASC) VISIBLE,
  CONSTRAINT `bill_fk_lease`
    FOREIGN KEY (`lease_id`)
    REFERENCES `friendlyplace`.`lease` (`lease_id`),
  CONSTRAINT `bill_fk_month`
    FOREIGN KEY (`pay_date`)
    REFERENCES `friendlyplace`.`month` (`pay_date`),
  CONSTRAINT `bill_fk_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `friendlyplace`.`unit` (`unit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
